### ISSUE TITLE
Release to CharmHub CI fails: no suitable 'build-on' environment

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/mysql-k8s-operator#125]
### Bug Description

From CI logs:
Run canonical/charming-actions/upload-charm@2.1.1
```shell
/usr/bin/sudo snap install charmcraft --classic --channel latest/stable
charmcraft 2.1.0 from Canonical** installed
/usr/bin/sudo charmcraft pack --destructive-mode --quiet
No suitable 'build-on' environment found in any 'bases' configuration.
```

### To Reproduce

Last passing CI run: https://github.com/canonical/mysql-k8s-operator/actions/runs/3613216881/jobs/6094949283
First failing CI run: https://github.com/canonical/mysql-k8s-operator/actions/runs/3638786440/jobs/6167166180

Note that the difference between the CI runs is:
Last passing runs on Ubuntu 20.04.5 LTS
First failing runs on Ubuntu 22.04.1 LTS

(CI job `runs-on: ubuntu-latest`)

**Comment by paulomach** [comment]
@carlcsaposs-canonical , I'm exploring [this](https://github.com/canonical/mysql-operator/blob/0bc2209cfc177a4d439adcf3425ec06de47c5a32/tests/integration/relations/test_database.py#L71) avenue to deal with this - test running right now

**Comment by paulomach** [comment]
@carlcsaposs-canonical , imho we can go only "22.04" for k8s

**Comment by paulomach** [comment]
@carlcsaposs-canonical , go for it. AFAIK there's no other mod required.
