### ISSUE TITLE
Missing dashboards with metrics about available storage

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/mysql-k8s-operator#235]
Please consider adding Grafana metric with the report about available storage.

Kubeflow (MLFlow) customers require to know how much space they have to perform experiments. We fully rely on MySQL DB to store all the info. Unfortunately, now in Grafana this metric is missing

**Comment by taurus-forever** [comment]
Hi @beliaev-maksim thank you for the request!
Q: do we have a general concept here? CC: @simskij 

For VM: the subordinate `grafana-agent` exports the general `System Resources` dashboard: 
![Screenshot from 2023-06-05 12-49-00](https://github.com/canonical/mysql-k8s-operator/assets/1928266/eed24ee1-0eb7-41cf-8fba-ad12e2dc006f)

For K8s: should DB charm add/support `System Resources` manually OR there will be (is?) some general K8s solution from Observability team? Tnx!

**Comment by simskij** [comment]
> Hi @beliaev-maksim thank you for the request! Q: do we have a general concept here? CC: @simskij
> 
> For VM: the subordinate `grafana-agent` exports the general `System Resources` dashboard: ![Screenshot from 2023-06-05 12-49-00](https://user-images.githubusercontent.com/1928266/243331368-eed24ee1-0eb7-41cf-8fba-ad12e2dc006f.png) ![Screenshot from 2023-06-05 12-51-42](https://user-images.githubusercontent.com/1928266/243331983-94a339b7-012e-44c7-a310-24a6efe0abf8.png)
> 
> For K8s: should DB charm add/support `System Resources` manually OR there will be (is?) some general K8s solution from Observability team? Tnx!

There **will** be support from the Kubernetes team to surface metrics about the cluster itself, which should include storage utilization through node_exporter. 

Currently, there is no such thing available for k8s, however.

**Comment by taurus-forever** [comment]
Yeap. The Charmed K8s is blind for all metrics normally provided by `node_exporter`:
![Screenshot from 2023-06-05 13-08-22](https://github.com/canonical/mysql-k8s-operator/assets/1928266/f4a80fdb-7fbc-483a-bd75-cd09bdc97617)

Some therefor makes no sense for K8s case. Moreover, `node_exporter` will actually be `pod_exporter`...
Do you need `K8s node metrics` is another question :-D

Just for the reference:
* https://devopscube.com/node-exporter-kubernetes/
* https://www.cloudforecast.io/blog/node-exporter-and-kubernetes/

**Comment by simskij** [comment]
> @simskij so, until K8s team provides the addon we are blind on storage side?

Correct 👍🏼

**Comment by paulomach** [comment]
Closing with won't fix
