### ISSUE TITLE
`AssertionError: assert 'primary' == 'secondary'` in self-healing integration test

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/mysql-k8s-operator#262]
https://github.com/canonical/mysql-k8s-operator/actions/runs/5610647342/job/15204710102#step:6:221

**Comment by paulomach** [comment]
This is due some flakiness that should have been addressed by [PR#272 ](https://github.com/canonical/mysql-k8s-operator/pull/272)
