### ISSUE TITLE
Charm trying fail to set `report_host` on scale up

### ISSUE THREAD

**Issue by paulomach** [canonical/mysql-k8s-operator#400]
Sunbean related [bug](https://bugs.launchpad.net/snap-openstack/+bug/2059774)

**Comment by nobuto-m** [comment]
Full debug log.

https://bugs.launchpad.net/snap-openstack/+bug/2059774/+attachment/5783568/+files/sunbeam-inspection-report-20240528_134403.tar.gz

**Comment by paulomach** [comment]
Thanks @nobuto-m
