### ISSUE TITLE
[RFE] binlog_expire_logs_seconds option 

### ISSUE THREAD

**Issue by pedrofragola** [canonical/mysql-k8s-operator#412]
[Feature request] 

The mysql-k8s charm currently uses the default parameter for binary log retention (binlog_expire_logs_seconds), which is set to rotate the logs after 30 days as per the documentation[0]. In some scenarios, such as when using Kubeflow, this binary log can fill up very quickly. It would be beneficial to have the ability to modify this configuration directly through Juju, allowing users to set this parameter permanently on the charm to accommodate their specific usage patterns.

[0] https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_binlog_expire_logs_seconds

**Comment by paulomach** [comment]
Hi @pedrofragola , we are discussing this and will fup here

**Comment by paulomach** [comment]
@pedrofragola we are going to change it to 7 days, which is inline with retention period for other logs

**Comment by pedrofragola** [comment]
@paulomach thanks for the heads-up :) ... Do you think for the next releases it will be possible to have an option to update this config using the charm option?

**Comment by paulomach** [comment]
@pedrofragola, an option is out of the cards for now

**Comment by paulomach** [comment]
@slapcat PR will be up today or tomorrow.

**Comment by paulomach** [comment]
@slapcat @pedrofragola I'll need to refactor the PR, for your benefit though. Our PM approved having a dedicated configuration parameter as per [comment](https://github.com/canonical/mysql-operator/pull/503#issuecomment-2275606513)

**Comment by paulomach** [comment]
@slapcat @pedrofragola Feature now published to channel `8.0/edge`
One can set charm configuration `binlog_retention_days` at a minimum of `1` day (default being `7` days).
Appreciate if you can test it.

**Comment by pedrofragola** [comment]
Hi @paulomach thanks for checking it ... I did the test using the edge channel:

mysql-k8s  8.0.37-0ubuntu0.22.04.3  active      1  mysql-k8s  8.0/edge     178  10.152.183.190  no       

juju config mysql-k8s binlog_retention_days=2

mysql> SHOW VARIABLES LIKE '%expire_logs%';
+-------------------------------+--------+
| Variable_name                 | Value  |
+-------------------------------+--------+
| binlog_expire_logs_auto_purge | ON     |
| binlog_expire_logs_seconds    | 172800 |
| expire_logs_days              | 0      |
+-------------------------------+--------+
3 rows in set (0.01 sec)


It worked... do you happen to know when this charm will be promoted to stable channel?

**Comment by paulomach** [comment]
> Hi @paulomach thanks for checking it ... I did the test using the edge channel:
> 
> mysql-k8s 8.0.37-0ubuntu0.22.04.3 active 1 mysql-k8s 8.0/edge 178 10.152.183.190 no
> 
> juju config mysql-k8s binlog_retention_days=2
> 
> mysql> SHOW VARIABLES LIKE '%expire_logs%'; +-------------------------------+--------+ | Variable_name | Value | +-------------------------------+--------+ | binlog_expire_logs_auto_purge | ON | | binlog_expire_logs_seconds | 172800 | | expire_logs_days | 0 | +-------------------------------+--------+ 3 rows in set (0.01 sec)
> 
> It worked... do you happen to know when this charm will be promoted to stable channel?

We will be releasing a candidate next week and ask test from sunbeam/kubeflow. We can promote as soon they validate it
