### ISSUE TITLE
Refactor scale down on units to use teardown events

### ISSUE THREAD

**Issue by shayancanonical** [canonical/mysql-k8s-operator#82]
There is currently a [juju bug](https://bugs.launchpad.net/juju/+bug/1951415) where teardown events are not fired when a unit is scaling down. This prevents the departing unit from removing itself from the cluster using `mysqlsh.remove_instance(self)`.

Since the unit departs before it can remove itself from the cluster, the juju leader unit has to use `mysqlsh.remove_instance(departed_unit, {force: true})` to remove the already departed unit. Furthermore, if there is a loss of quorum, the charm uses `mysqlsh.force_quorum_using_partition_of(first_online_unit)`. This is not the ideal solution, and this issue has been created to keep track of the juju bug resolution and replace the scale down logic to use teardown events when they are firing.

**Comment by taurus-forever** [comment]
@shayancanonical can you please re-check this on pre-2.9.43 with fixed scale-down K8s logic. Tnx!

**Comment by paulomach** [comment]
Closed on #249
